apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookmarky-dev
resources:
  - ../../base
  - network.yaml
  # - secrets.yaml
images:
  - name: harbor.squid-ink.us/politeauthority/bookmarky
    newTag: stage-latest
patches:
  - target:
      kind: Deployment
      name: bookmarky-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: add
        path: /spec/template/spec/containers/0/command
        value: ["tail", "-f", "/dev/null"]
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JWT_EXPIRE_MINUTES
          value: "5760"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: BOOKMARKY_ENV
          value: "dev"
      - op: remove
        path: /spec/template/spec/initContainers
