apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookmarky-dev
resources:
  - ../../base
  - storage.yaml
  # - secrets.yaml
images:
  - name: harbor.squid-ink.us/politeauthority/bookmarky-api
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: bookmarky-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: add
        path: /spec/template/spec/containers/0/command
        value: ["tail", "-f", "/dev/null"]
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JWT_EXPIRE_MINUTES
          value: "5760"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: BOOKMARKY_ENV
          value: "dev"
      - op: remove
        path: /spec/template/spec/initContainers
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: bookmarky-images-dev
  - target:
      kind: Ingress
      name: bookmarky-api
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
      - op: replace
        path: /spec/ingressClassName
        value: nginx-public
      - op: replace
        path: /spec/rules/0/host
        value: api.bookmarky-dev.alix.lol
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.bookmarky-dev.alix.lol
