apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookmarky-images-dev
  labels:
    app.kubernetes.io/instance: bookmarky
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/k8s/bookmarky/bookmarky-dev
    server: 192.168.50.52
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookmarky-images-dev
  labels:
    app.kubernetes.io/instance: bookmarky
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: bookmarky-images-dev
