apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarky-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarky-api
  template:
    metadata:
      labels:
        app: bookmarky-api
    spec:
      imagePullSecrets:
        - name: harbor-registry
      securityContext:
        fsGroup: 1003
      initContainers:
        - name: bookmarky-migrations
          image: harbor.squid-ink.us/politeauthority/bookmarky-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: BOOKMARKY_DB_HOST
              valueFrom:
                secretKeyRef:
                  key: BOOKMARKY_DB_HOST
                  name: bookmarky-creds
            - name: BOOKMARKY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: bookmarky-creds
                  key: BOOKMARKY_DB_NAME
            - name: BOOKMARKY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: bookmarky-creds
                  key: BOOKMARKY_DB_USER
            - name: BOOKMARKY_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bookmarky-creds
                  key: BOOKMARKY_DB_PASS
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: BOOKMARKY_ENV
              value: "prod"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "250m"
          command: ["python3", "/app/bookmarky/migrations/migrate.py"]
      containers:
        - name: bookmarky-api
          image: harbor.squid-ink.us/politeauthority/bookmarky-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: BOOKMARKY_DB_HOST
              valueFrom:
                secretKeyRef:
                  key: BOOKMARKY_DB_HOST
                  name: bookmarky-creds
            - name: BOOKMARKY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: bookmarky-creds
                  key: BOOKMARKY_DB_NAME
            - name: BOOKMARKY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: bookmarky-creds
                  key: BOOKMARKY_DB_USER
            - name: BOOKMARKY_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bookmarky-creds
                  key: BOOKMARKY_DB_PASS
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: BOOKMARKY_ENV
              value: "prod"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bookmarky-creds
                  key: SECRET_KEY
            - name: IMAGE_DIR
              value: "/images"
          volumeMounts:
            - name: bookmarky-images
              mountPath: /images
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 240
      volumes:
        - name: bookmarky-images
          persistentVolumeClaim:
            claimName: bookmarky-images-prod
